# Generated by Django 5.1.3 on 2024-12-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_manager_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='category',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('park', 'Park')], default='unassigned', max_length=20),
        ),
    ]
