# Generated by Django 5.1.3 on 2024-12-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_manager_is_active_manager_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
